# Site settings
title: "Code, Bagels and Gibberish"
email: ""
description: "A small space for a newbie dev. Small and silly projects are always ongoing. Enjoy!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: healthycola
github_username:  healthycola
excerpt_separator: <!--more-->
comments: true
# Build settings
markdown: kramdown
permalink: pretty